export default [
	{
		path: '/about/',
		component: require('./pages/about.vue')
	},
	{
		path: '/search/',
		component: require('./pages/search.vue')
	},
	{
		path:"/register/",
		component:require('./pages/register.vue')
	},
	{
		path:"/login/",
		component:require('./pages/login.vue')
	},
	{
		path:"/setting/",
		component:require('./pages/settingView.vue')
	},
	{
		path:"/user/resetPassword/",
		component:require('./pages/resetPassword.vue')
	},
	{
		path:"/user/userAgreement/",
		component:require('./pages/userAgreement.vue')
	},
	{
		path:"/userAdvice/",
		component:require('./pages/userAdvice.vue')
	},
	{
		path:"/evalDetail/:pid",
		component:require('./pages/evalDetail.vue')
	},
	{
		path:"/evalGoods/",
		component:require('./pages/evalGoods.vue')
	},	
	{
		path:"/postDetail/:pid",
		component:require('./pages/postDetails.vue')
	},
	{
		path:"/comments/:pid",
		component:require('./pages/comments.vue')
	},
	{
		path:"/postCreate/",
		component:require('./pages/postCreate.vue')
	},
	{
		path:"/news/",
		component:require('./pages/news.vue')
	},
	{
		path:"/chat/:pid",
		component:require('./pages/chat.vue')
	},
	{
		path:"/fans/",
		component:require('./pages/fans.vue')
	},
	{
		path:"/follows/",
		component:require('./pages/follows.vue')
	},
	{
		path:"/personSetting/",
		component:require('./pages/personSetting.vue')
	},
	{
		path:"/otherInfo/:pid",
		component:require('./pages/otherInfo.vue')
	},
	{
		path:"/myCollect/",
		component:require('./pages/my/myCollect.vue')
	},
	{
		path:"/myPost/",
		component:require('./pages/my/myPost.vue')
	},
	{
		path:"/changePersonInfo/",
		component:require('./pages/my/changePersonInfo.vue')
	},
	{
		path:"/changeAvatar/",
		component:require('./pages/my/changeAvatar.vue')
	},
	{
		path:"/userFans/:pid",
		component:require('./pages/my/userFans.vue')
	},
	{
		path:"/userFollows/:pid",
		component:require('./pages/my/userFollows.vue')
	},
	{
		path:"/userAgreement/",
		component:require('./pages/userAgreement.vue')
	},
	{
		path:"/personalBind/",
		component:require('./pages/personalBind.vue')
	}
]
